name: Build and publish Docker

on:
  push:
    branches: [ master , develop , docker-compose ]
  pull_request:
    branches: [ master , develop , docker-compose ]

jobs:
  push_client_to_registry:
    name: Push Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Client repo
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push Client to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hhrib/tacs-utn
          tags: ${{ steps.vars.outputs.sha_short }}
          tag_with_ref: true
          buildoptions: "-f front-game/Dockerfile"
  push_server_to_registry:
    name: Push Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Server repo
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push Server to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hhrib/tacs-utn
          tags: ${{ steps.vars.outputs.sha_short }}
          tag_with_ref: true
          buildoptions: "-f game/Dockerfile"
