name: Build and publish Docker

on:
  push:
    branches: [ master , develop , docker-compose ]
  pull_request:
    branches: [ master , develop , docker-compose ]

jobs:
  push_client_to_registry:
    name: Push Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Client repo
        uses: actions/checkout@v2
     - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      #- name: Set outputs
      # id: vars
      # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Push Client to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: front-game
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #repository: hhrib/tacs-client
          repository: hhrib/tacs_client
          #tags: latest
          #tags: front-${{ steps.vars.outputs.sha_short }}
          tags: ${{ BRANCH_NAME }}
          dockerfile: front-game/Dockerfile
          image_name:  hhrib/tacs_client
          #buildoptions: ""
  push_server_to_registry:
    name: Push Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Server repo
        uses: actions/checkout@v2.3.2
      #- name: Set outputs
      #  id: vars
      #  run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push Server to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: game
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #repository: hhrib/tacs-client
          repository: hhrib/tacs_server
          #tags: latest
          #tags: front-${{ steps.vars.outputs.sha_short }}
          tags: server , ${{ steps.extract_branch.outputs.branch }}
          dockerfile: game/Dockerfile
          image_name:  hhrib/tacs_server