name: ci

on:
  push:
    branches: docker-compose

jobs:
  push_client_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tacs-utn/client:latest
          path: front-game
          file: front-game/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}