name: Build and publish Docker

on:
  push:
    branches: [ master , develop , docker-compose ]
  pull_request:
    branches: [ master , develop , docker-compose ]

jobs:
  push_client_to_registry:
    name: Push Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Client repo
        uses: actions/checkout@v2
      - name: Push Client to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hhrib/tacs-utn
          tags: ${{ github.sha }}
          tag_with_ref: true
          buildoptions: "-f front-game/Dockerfile"
  push_server_to_registry:
    name: Push Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Server repo
        uses: actions/checkout@v2
      - name: Push Server to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hhrib/tacs-utn
          tags: ${{ github.sha[0:8] }}
          tag_with_ref: true
          buildoptions: "-f game/Dockerfile"
