name: ci

on:
  push:
    branches: docker-compose

jobs:
  push_client_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Check out the Client repo
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tacs-utn/client:latest
          repository: hhrib/tacs-utn
          dockerfile: Dockerfile-front
          image_name: tacs-utn/client
          file: Dockerfile-front
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}